default: &default
  # adapter: sqlite3
  # pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  # timeout: 5000
  adapter: mysql2
  charset: utf8
  encoding: utf8
  database: bookshelf_db
  pool: 5
  username: ryota
  password: ziziiyouti
  host: localhost
  
development:
  <<: *default

test:
  <<: *default
  database: bookshelf_test

production:
  <<: *default
  database: bookshelf_production